var dataProductos = {
    "datacodigo": "",
    "productos": [
        {
            "id": 1,
            "image": "",
            "name": "VIGACO",
            "product": "VINO ESPECIAL",
            "date": "2003",
            "category": "Vinos",
            "capacity": "750ml",
            "description": "Tempranillo No es una variedad rica en taninos, por lo que los vinos son finos, amables y sedosos en boca. Además, presentan un color rojo intenso y con matices violáceos en su juventud y aromas a fruta roja madura, frutos silvestres, vainilla, tabaco, chocolate y toques herbáceos y florales.",
            "price": 0,
            "winePairing": "Prefiere consumir vegetales asados, carnes curadas y quesos, tapas y carnes rojas. Algunos platos que quedarían perfectos con esta opción son paella, jamón serrano, chorizos, pizza, burritos y tacos. La razón de esto es porque la acidez del vino no es tan pronunciada y los sabores que inundan al paladar son a cereza y salsa de tomate.",
            "code": 36,
        },
        {
            "id": 2,
            "image": "",
            "name": "ROSÉ",
            "product": "VINO ESPECIAL",
            "date": "2000",
            "category": "Vinos",
            "capacity": "750ml",
            "description": "Garnacha o Grenache. La uva garnacha se originó muy probablemente en la región de Aragón, en el norte de España. La garnacha se usa a menudo como un componente de mezcla, añadiendo cuerpo y dulzor de frutas al vino.",
            "price": 0,
            "winePairing": "Roquefort, Gorgonzola, Stilton o Cabrales son ideales para acompañar vinos de cosechas tardías, dulces naturales o fortificados.",
            "code": 36,
        },
        {
            "id": 3,
            "image": "",
            "name": "ZOHE",
            "product": "VINO ESPECIAL",
            "date": "2001",
            "category": "Vinos",
            "capacity": "750ml",
            "description": "Malbec. Uva tinta procedente del suroeste de Francia, aunque es la uva emblemática de Argentina, donde se ha adaptado perfectamente. Produce vinos tintos de cuerpo medio, agradables de tomar por ser muy equilibrados con aromas a mora, violetas, ciruela, cacao y tabaco.            ",
            "price": 0,
            "winePairing": "La carne cocida al horno combina muy bien con un Malbec de alta gama.",
            "code": 36,
        },
        {
            "id": 4,
            "image": "",
            "name": "DEUX BONHEUR",
            "product": "VINO TINTO",
            "date": "2018",
            "category": "Vinos",
            "capacity": "750ml",
            "description": "Nebbiolo por su parte, en el Nuevo Mundo los vinos son, generalmente, de capa media alta y presentan un mayor cuerpo, con una intensidad aromática más potente y toques más avainillados y a fruta madura.",
            "price": 0,
            "winePairing": " lo mejor que puedes escoger es un vino tinto potente y estructurado (crianzas o reservas), ya que la mayoría de estos platos tienen presencia de algún embutido, como el chorizo o el tocino, lo que les proporciona una consistencia grasosa. Los vinos de esta clase son los más indicados por su concentración de taninos, lo que ayuda a lidiar con la grasa y la untuosidad del plato. ",
            "code": 36,
        },
        {
            "id": 5,
            "image": "",
            "name": "LAMAF",
            "product": "VINO TINTO",
            "date": "2018",
            "category": "Vinos",
            "capacity": "750ml",
            "description": "Tempranillo. Obtiene su nombre porque la cosecha de uvas es recogida más temprano que en otras variedades, por lo que son ideales para vinos jóvenes, de sabor afrutado y con un hermoso color rubí.",
            "price": 0,
            "winePairing": "Lo ideal es que lo dulce vaya con lo dulce. Tortas, postres, frutas y elaboraciones con cierto tenor dulzón, combinan a la perfecció.",
            "code": 36,
        },
        {
            "id": 6,
            "image": "",
            "name": "RAMÉ",
            "product": "VINO TINTO",
            "date": "2019",
            "category": "Vinos",
            "capacity": "750ml",
            "description": "Merlot. Esta uva procedente del sudoeste de Francia es la segunda cepa tradicional y en importancia de los grandes vinos de Burdeos. Los vinos de Merlot son vinos con cierta intensidad cromática, con grado alcohólico medio alto y con ligeros aromas de cereza, ciruela, chocolate, vainilla, regaliz, tabaco, de cuerpo medio y taninos amables.",
            "price": 0,
            "winePairing": "El vacío combina inmejorablemente con un Merlot con crianza en roble.",
            "code": 36,
        },
        {
            "id": 7,
            "image": "",
            "name": "FRENESÍ,",
            "product": "VINO TINTO",
            "date": "2018",
            "category": "Vinos",
            "capacity": "750ml",
            "description": "2 tipos de uva",
            "price": 0,
            "winePairing": "Por su alto contenido graso, los cortes de cerdo combinan muy bien con blends tintos estructurados",
            "code": 36,
        },
        {
            "id": 8,
            "image": "",
            "name": "SERC",
            "product": "VINO TINTO",
            "date": "2019",
            "category": "Vinos",
            "capacity": "750ml",
            "description": "Malbec jugosos, frutales y con taninos delicados.Uva tinta procedente del suroeste de Francia, aunque es la uva emblemática de Argentina, donde se ha adaptado perfectamente.",
            "price": 0,
            "winePairing": "Para acompañar carnes magras, como el cuadril o el lomo",
            "code": 36,
        },
        {
            "id": 9,
            "image": "",
            "name": "BELLE VIE",
            "product": "VINO BLANCO",
            "date": "2021",
            "category": "",
            "capacity": "750ml",
            "description": "Es una uva de gran intensidad aromática que produce vinos de baja acidez, tropicales, dulces, florales y con un toque picante. Sus aromas principales recuerdan a mandarina, rosas, jengibre, lichis y toronja. Marida muy bien con platillos especiados como comida asiática o marroquí.",
            "price": 0,
            "winePairing": "Quesos de cabra muy frescos son la combinacion perfecta para un vino blanco, estos puedan igualar su acidez característica sin perder sus atributos.",
            "code": 36,
        },
        {
            "id": 10,
            "image": "",
            "name": "FRAICHE",
            "product": "VINO BLANCO",
            "date": "2021",
            "category": "Vinos",
            "capacity": "750ml",
            "description": "Chardonnay. Originaria de Borgoña, aunque también sobresale en California (Estados Unidos) es la uva blanca más emblemática en todo el mundo. Produce vinos blancos con aromas a manzana, piña, mandarina, miel, mantequilla y notas minerales.",
            "price": 0,
            "winePairing": "En líneas generales, los Chardonnay frescos y aromáticos, maridan muy bien con pollo asado o al horno. ",
            "code": 36,
        },
        {
            "id": 11,
            "image": "",
            "name": "AGAPI",
            "product": "VINO ROSADO",
            "date": "2023",
            "category": "Vinos",
            "capacity": "750ml",
            "description": "Para elaborar el vino rosado no se utiliza uva rosa. La Garnacha es una de las variedades de uvas tintas que se emplean para producir este vino.",
            "price": 0,
            "winePairing": "Las etiquetas rosés son gratas opciones para armonizar, Ensaladas de camarones, frutos de mar, mariscos; Pescados magros y grasos.",
            "code": 36,
        },
        {
            "id": 12,
            "image": "",
            "name": "FELICITÉ",
            "product": "VINO ESPUMANTE",
            "date": "2022",
            "category": "Vinos",
            "capacity": "750ml",
            "description": "Principalmente, se utilizan las uvas Chardonnay, Pinot Noir y Pinot Meunier.",
            "price": 0,
            "winePairing": "Los espumantes son los compañeros ideales de rolls, sashimis y nigiris.",
            "code": 36,
        },
        {
            "id": 13,
            "image": "",
            "name": "Glenlivet 36 Year (1981), Signatory Vintage",
            "product": "Whisky 36 Años",
            "date": "",
            "category": "Whiskys",
            "capacity": "700ml",
            "description": "36 años (destilado el 12 de diciembre de 1981, embotellado el 18 de abril de 2018).",
            "price": 370000,
            "winePairing": "Entre más cacao contenga el chocolate de tu elección, será un mejor acompañante para tu whisky. No tienes que comer una barra de chocolate como tal, sino saborearlo en presentaciones como bombones y mousse.",
            "code": 27,
        },
        {
            "id": 14,
            "image": "",
            "name": "Dewar's Double Double",
            "product": "Whisky 36 Años",
            "date": "",
            "category": "Whiskys",
            "capacity": "500ml",
            "description": "El whisky de malta mezclado Dewar's Double Double 36 años tiene notas de sabor de melocotones maduros, aceite de coco y vainilla, todo envuelto en una textura suave y cremosa que es a la vez equilibrada y compleja.",
            "price": 480000,
            "winePairing": "la pareja ideal para platillos como el sushi, el salmón ahumado o el sashimi.",
            "code": 27,
        },
        {
            "id": 15,
            "image": "",
            "name": "Linkwood 24 Years Old Signatory",
            "product": "Whisky 24 Años",
            "date": "",
            "category": "Whiskys",
            "capacity": "700ml",
            "description": "Signatory Vintage que se maduró en un par de toneles durante 24 años, antes de ser embotellado en abril de 2022 como parte de su Cask Strength Collection.",
            "price": 74100,
            "winePairing": "Se pueden acompañar cortes a la parrilla, ya sea de vaca o cerdo.",
            "code": 27,
        },
        {
            "id": 16,
            "image": "",
            "name": "Whisky Single Malt Cardhu 18 Años",
            "product": "Whisky 18 Años",
            "date": "",
            "category": "Whiskys",
            "capacity": "700ml",
            "description": "Color ámbar tostado. Notas de vainilla, caramelo, miel y nueces. Toque de naranja y regaliz, un poco de té negro. Acabado corto a mediano, limpio, con más dulce de leche y té de hierbas.",
            "price": 31900,
            "winePairing": "Los postres en general se fusionan muy bien con el sabor del whisky. Para mejorar la experiencia recomendamos postres muy dulces o con toques de nuez.",
            "code": 27,
        },
        {
            "id": 17,
            "image": "",
            "name": "Whisky Buchanans 18 Años",
            "product": "Whisky 18 Años",
            "date": "",
            "category": "Whiskys",
            "capacity": "750ml",
            "description": "El Buchanan's 18 años se añeja durante un mínimo de 6 años que, sumados a los 12 como mínimo que tienen los whiskies que lo componen, dan 18 años de excelente añejamiento.",
            "price": 57890,
            "winePairing": "Entre las mejores opciones que resalta están los quesos blancos tipo mozzarella, el aguacate, salmones ahumados, carpaccios, nueces, láminas de pera, sushi, jamón ibérico, ceviches",
            "code": 27,
        },
        {
            "id": 18,
            "image": "",
            "name": "Whisky Buchanans 12 Años",
            "product": "Whisky 12 Años",
            "date": "",
            "category": "Whiskys",
            "capacity": "750ml",
            "description": "",
            "price": 0,
            "winePairing": "",
            "code": 27,
        },
        {
            "id": 19,
            "image": "",
            "name": "Cardhu 12 Años",
            "product": "Whisky 12 Años",
            "date": "",
            "category": "Whiskys",
            "capacity": "",
            "description": "",
            "price": 0,
            "winePairing": "",
            "code": 27,
        },
        {
            "id": 20,
            "image": "",
            "name": "Whisky Aberlour 12 años",
            "product": "Whisky 12 Años",
            "date": "",
            "category": "Whiskys",
            "capacity": "700ml",
            "description": "",
            "price": 0,
            "winePairing": "",
            "code": 27,
        },
        {
            "id": 21,
            "image": "",
            "name": "Whisky Aultmore 12 Años",
            "product": "Whisky 12 Años",
            "date": "",
            "category": "Whiskys",
            "capacity": "750ml",
            "description": "",
            "price": 0,
            "winePairing": "",
            "code": 27,
        },
        {
            "id": 22,
            "image": "",
            "name": "CERVEZA ROJA",
            "product": "CERVEZA ROJA",
            "date": "2023",
            "category": "Cervezas",
            "capacity": "50 Litros",
            "description": "Esta cerveza, este color, se origino en Escocia, y esta pelirroja se encuentra desde hace siglos entre nosotros. En su elaboración predominan la malta de cebada y su color rubí, y a diferencia de la cerveza negra, por ejemplo, casi no incluye lúpulo. Se suele distinguir por sus aromas frutales. La cerveza roja mas popular es la variedad conocida como Scotch Ale, así como también la Red Ale que proviene de Irlanda y en la que predomina la malta caramelo y tostada, para así reforzar su sabor dulce.",
            "price": 0,
            "winePairing": "La cerveza ámbar o tostada es una cerveza roja y se elabora con una mezcla de maltas predominantemente oscuras. Estas cervezas pueden ser de fermentación baja o alta y su color varía del cobre al ámbar y al bronce oscuro. Éstas son las combinaciones más equilibradas: quesos a la parrilla, carne de cerdo, y hamburguesas.",
            "code": 3,
        },
        {
            "id": 23,
            "image": "",
            "name": "CERVEZA ROJA",
            "product": "CERVEZA ROJA",
            "date": "2023",
            "category": "Cervezas",
            "capacity": "30 Litros",
            "description": "Esta cerveza, este color, se origino en Escocia, y esta pelirroja se encuentra desde hace siglos entre nosotros. En su elaboración predominan la malta de cebada y su color rubí, y a diferencia de la cerveza negra, por ejemplo, casi no incluye lúpulo. Se suele distinguir por sus aromas frutales. La cerveza roja mas popular es la variedad conocida como Scotch Ale, así como también la Red Ale que proviene de Irlanda y en la que predomina la malta caramelo y tostada, para así reforzar su sabor dulce.",
            "price": 0,
            "winePairing": "La cerveza ámbar o tostada es una cerveza roja y se elabora con una mezcla de maltas predominantemente oscuras. Estas cervezas pueden ser de fermentación baja o alta y su color varía del cobre al ámbar y al bronce oscuro. Éstas son las combinaciones más equilibradas: quesos a la parrilla, carne de cerdo, y hamburguesas.",
            "code": 3,
        },
        {
            "id": 24,
            "image": "",
            "name": "CERVEZA ROJA",
            "product": "CERVEZA ROJA",
            "date": "2023",
            "category": "Cervezas",
            "capacity": "20 Litros",
            "description": "Esta cerveza, este color, se origino en Escocia, y esta pelirroja se encuentra desde hace siglos entre nosotros. En su elaboración predominan la malta de cebada y su color rubí, y a diferencia de la cerveza negra, por ejemplo, casi no incluye lúpulo. Se suele distinguir por sus aromas frutales. La cerveza roja mas popular es la variedad conocida como Scotch Ale, así como también la Red Ale que proviene de Irlanda y en la que predomina la malta caramelo y tostada, para así reforzar su sabor dulce.",
            "price": 0,
            "winePairing": "La cerveza ámbar o tostada es una cerveza roja y se elabora con una mezcla de maltas predominantemente oscuras. Estas cervezas pueden ser de fermentación baja o alta y su color varía del cobre al ámbar y al bronce oscuro. Éstas son las combinaciones más equilibradas: quesos a la parrilla, carne de cerdo, y hamburguesas.",
            "code": 3,
        },
        {
            "id": 25,
            "image": "",
            "name": "Cuvée Royale Rouge",
            "product": "vino tinto",
            "date": "2021",
            "category": "tintos",
            "capacity": "750ml",
            "description": "Sangiovese: Las uvas se recolectan y se fermentan en tanques de acero inoxidable durante 1-2 semanas. Después de la fermentación, el vino se traslada a barricas de roble italiano para añejarse durante 12-24 meses.",
            "price": 10000,
            "winePairing": "Este vino elegante y suave se marida bien con platos de carne de cerdo o con platos de pasta con salsa de tomate.",
        },
        {
            "id": 26,
            "image": "",
            "name": "Grandeur Noir",
            "product": "vino tinto",
            "date": "2019",
            "category": "tintos",
            "capacity": "750ml",
            "description": "Zinfandel: Las uvas se recolectan y se fermentan en barricas de roble durante 2-3 semanas. Después de la fermentación, el vino se traslada a barricas de roble americano para añejarse durante 12-18 meses.",
            "price": 19000,
            "winePairing": "Un vino sofisticado y con cuerpo que se marida bien con platos de carne roja, como el filete o la carne de buey.",
        },
        {
            "id": 27,
            "image": "",
            "name": "Vintage Rouge",
            "product": "vino tinto",
            "date": "2022",
            "category": "tintos",
            "capacity": "750ml",
            "description": "Tempranillo: Las uvas se recolectan y se fermentan en tanques de acero inoxidable durante 1-2 semanas. Después de la fermentación, el vino se traslada a barricas de roble americano para añejarse durante 12-24 meses.",
            "price": 18000,
            "winePairing": "Un vino elegante y suave que se marida bien con platos de carne de ternera, como el filete o la entraña.",
        },
        {
            "id": 28,
            "image": "",
            "name": "Domaine Grandeur",
            "product": "vino tinto",
            "date": "2022",
            "category": "tintos",
            "capacity": "750ml",
            "description": "Syrah: Las uvas se recolectan y se fermentan en barricas de roble durante 2-3 semanas. Después de la fermentación, el vino se traslada a barricas de roble francés para añejarse durante 12-18 meses.",
            "price": 43000,
            "winePairing": "Este vino con notas a frutos del bosque se marida bien con platos de carne de cerdo o con platos de pasta con salsa de tomate.",
        },
        {
            "id": 29,
            "image": "",
            "name": "Signature Rouge",
            "product": "vino tinto",
            "date": "2022",
            "category": "tintos",
            "capacity": "750ml",
            "description": "Pinot Noir: Las uvas se recolectan y se fermentan en tanques de acero inoxidable durante 1-2 semanas. Después de la fermentación, el vino se traslada a barricas de roble francés para añejarse durante 6-18 meses.",
            "price": 48000,
            "winePairing": "Este vino equilibrado y aromático es ideal para acompañar platos de caza, como el jabalí o el ciervo.",
        },
        {
            "id": 30,
            "image": "",
            "name": "Cuvée Prestige Noir",
            "product": "vino tinto",
            "date": "2020",
            "category": "especiales",
            "capacity": "750ml",
            "description": "Malbec: Las uvas se recolectan y se fermentan en tanques de acero inoxidable durante 2-3 semanas. Después de la fermentación, el vino se traslada a barricas de roble americano para añejarse durante 12-18 meses.",
            "price": 90000,
            "winePairing": " Este vino de gran cuerpo y sabor intenso se marida bien con carnes rojas como la ternera o el buey.",
        },
        {
            "id": 31,
            "image": "",
            "name": "Éclat Rouge",
            "product": "vino tinto",
            "date": "2021",
            "category": "especiales",
            "capacity": "750ml",
            "description": "Merlot: Las uvas se recolectan y se fermentan en tanques de acero inoxidable durante 1-2 semanas. Después de la fermentación, el vino se traslada a barricas de roble para añejarse durante 6-18 meses.",
            "price": 95000,
            "winePairing": "Un vino sofisticado y aromático que se puede maridar con platos de carnes blancas como el pollo o el pavo, o con platos de caza.",
        },
        {
            "id": 32,
            "image": "",
            "name": "gran reserva royale",
            "product": " Vino tinto",
            "date": "2020",
            "category": "especiales",
            "capacity": "750ml",
            "description": "Cabernet Sauvignon: Las uvas se recolectan y se fermentan en barricas de roble durante 2-3 semanas. Después de la fermentación, el vino se traslada a barricas de roble francés para añejarse durante 12-18 meses.",
            "price": 80000,
            "winePairing": "Este vino elegante y con cuerpo combina bien con platos de carne roja como un chuletón o un asado de cordero.",
        },
    ]
}